name: Pull Request Checks

on:
  pull_request:
    branches:
      - master

jobs:
  pull_request_checks:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17 and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true
          cache: 'maven'

      - name: Change to project directory
        run: cd bingo-online

      - name: Build with Maven
        run: mvn -B -f bingo-online/pom.xml clean install

      - name: Run unit tests
        run: mvn -f bingo-online/pom.xml test

      - name: Check test status
        if: failure()
        run: exit 1
