name: Pipeline

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - main
    paths:
      - bingo-online/**

jobs:
  TEST_VALIDATION:
    name: 1 - VALIDATING UNIT AND INTEGRATION TESTS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17 and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true
          cache: 'maven'

      - name: Change to project directory
        run: cd bingo-online

      - name: Build with Maven
        run: mvn -B -f bingo-online/pom.xml clean install

      - name: Run unit tests
        run: mvn -f bingo-online/pom.xml test

  create_pull_request:
    name: 2 - CREATE PULL REQUEST
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get branch name
        id: branch_name
        run: echo "::set-output name=name::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Feature: Implementing new feature on ${{ steps.branch_name.outputs.name }}"
          body: "This pull request was automatically generated by a commit in a feature branch."
          branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
